version: '3.1'

services:
  nova-environment-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - nova-environment-service-node-modules:/opt/npm
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      NODE_PORT: 3001

  mongo-environment:
    image: mongo
    restart: always
    volumes:
      - mongo-environment-data:/data/db

  mongo-admin-environment:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo-environment:27017/

volumes:
  mongo-environment-data:
  nova-environment-service-node-modules:
